### ISSUE TITLE
Demo and small suggestion for std::string support

### ISSUE THREAD

**Issue by ocornut** [MadLadSquad/UntitledImGuiTextUtils#1]
Hello :)

In the spirit of dear imgui it would be nice to have a demo function for this, which is easy to run to showcase most features.

Another suggestion would be to add a separate, short `UImGuiTextUtilsStdString.hpp` which includes `<string>` and provide all the alternate entry points using std::string. The function could be inlined in that file as well. This would make the main header terser and may be attractive to people who don't want to use std::string in their codebase.

**Comment by Madman10K** [comment]
@ocornut Thanks a lot for the feedback! I will add this today

**Comment by Madman10K** [comment]
Added [demo window](https://github.com/MadLadSquad/UntitledImGuiTextUtils/wiki/Installation-and-configuration#testing-out-the-library) and made C++ strings [opt-out + customisable](https://github.com/MadLadSquad/UntitledImGuiTextUtils/wiki/Installation-and-configuration#configuration).

These commits will be featured in release v1.1.0.0, which will be live in a few minutes. Thanks for contributing to the project :)
